spring:
  application:
    name: user-service
  profiles:
    active: default
  cloud:
    config:
      uri: http://localhost:8888
  config:
    import: "configserver:http://localhost:8888"

server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
