spring:
  application:
    name: hotel-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/hotel-db

server:
  port: 8081

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka